"""empty message

Revision ID: 2852e4dde7ae
Revises: b9a94ba94dfc
Create Date: 2019-11-19 02:44:33.271022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2852e4dde7ae'
down_revision = 'b9a94ba94dfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('API_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('_200', sa.Integer(), nullable=True),
    sa.Column('_201', sa.Integer(), nullable=True),
    sa.Column('_400', sa.Integer(), nullable=True),
    sa.Column('_401', sa.Integer(), nullable=True),
    sa.Column('_403', sa.Integer(), nullable=True),
    sa.Column('_404', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('API_info')
    # ### end Alembic commands ###
