"""empty message

Revision ID: 8359e5ba410a
Revises: 
Create Date: 2019-11-25 05:01:19.790881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8359e5ba410a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('genre', sa.String(), nullable=True),
    sa.Column('actors', sa.String(), nullable=True),
    sa.Column('director', sa.String(), nullable=True),
    sa.Column('release_date', sa.String(), nullable=True),
    sa.Column('budget', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('status_tracker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('_200', sa.Integer(), nullable=True),
    sa.Column('_201', sa.Integer(), nullable=True),
    sa.Column('_400', sa.Integer(), nullable=True),
    sa.Column('_401', sa.Integer(), nullable=True),
    sa.Column('_403', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('status_tracker')
    op.drop_table('movie')
    # ### end Alembic commands ###
