"""empty message

Revision ID: b1b82069005d
Revises: 2852e4dde7ae
Create Date: 2019-11-19 03:41:13.038925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1b82069005d'
down_revision = '2852e4dde7ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('API_info')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('API_info',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('_200', sa.INTEGER(), nullable=True),
    sa.Column('_201', sa.INTEGER(), nullable=True),
    sa.Column('_400', sa.INTEGER(), nullable=True),
    sa.Column('_401', sa.INTEGER(), nullable=True),
    sa.Column('_403', sa.INTEGER(), nullable=True),
    sa.Column('_404', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
